services:
  - type: web
    name: DAIMA-MD
    env: node
    branch: main
    repo: https://github.com/sataniceypz/Izumi-v3.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: WORK_TYPE
        value: public 
      - key: SERVER
        value: render
      - key: CAPTION
        value: DAIMA-ğ—«ğ——
      - key: SUDO
        value: 256789810043
